name = input ('Please type your name: ')
color = input ('Please type your favorite color: ')
number = input ('Please type your favorite number: ')
print ('Your name is: ')
print (name,'!')
print ('Your favorite color is: ')
print (color,'!')
print ('Your favorite number is: ')
print (number,'!')

